module ActiveHash
  class Prefecture < ActiveHash::Base
    self.data = [
      { id: 1, name: '北海道', romanized_name: 'Hokkaido' },
      { id: 2, name: '青森県', romanized_name: 'Aomori' },
      { id: 3, name: '岩手県', romanized_name: 'Iwate' },
      { id: 4, name: '宮城県', romanized_name: 'Miyagi' },
      { id: 5, name: '秋田県', romanized_name: 'Akita' },
      { id: 6, name: '山形県', romanized_name: 'Yamagata' },
      { id: 7, name: '福島県', romanized_name: 'Fukushima' },
      { id: 8, name: '茨城県', romanized_name: 'Ibaraki' },
      { id: 9, name: '栃木県', romanized_name: 'Tochigi' },
      { id: 10, name: '群馬県', romanized_name: 'Gunma' },
      { id: 11, name: '埼玉県', romanized_name: 'Saitama' },
      { id: 12, name: '千葉県', romanized_name: 'Chiba' },
      { id: 13, name: '東京都', romanized_name: 'Tokyo' },
      { id: 14, name: '神奈川県', romanized_name: 'Kanagawa' },
      { id: 15, name: '新潟県', romanized_name: 'Niigata' },
      { id: 16, name: '富山県', romanized_name: 'Toyama' },
      { id: 17, name: '石川県', romanized_name: 'Ishikawa' },
      { id: 18, name: '福井県', romanized_name: 'Fukui' },
      { id: 19, name: '山梨県', romanized_name: 'Yamanashi' },
      { id: 20, name: '長野県', romanized_name: 'Nagano' },
      { id: 21, name: '岐阜県', romanized_name: 'Gifu' },
      { id: 22, name: '静岡県', romanized_name: 'Shizuoka' },
      { id: 23, name: '愛知県', romanized_name: 'Aichi' },
      { id: 24, name: '三重県', romanized_name: 'Mie' },
      { id: 25, name: '滋賀県', romanized_name: 'Shiga' },
      { id: 26, name: '京都府', romanized_name: 'Kyoto' },
      { id: 27, name: '大阪府', romanized_name: 'Osaka' },
      { id: 28, name: '兵庫県', romanized_name: 'Hyogo' },
      { id: 29, name: '奈良県', romanized_name: 'Nara' },
      { id: 30, name: '和歌山県', romanized_name: 'Wakayama' },
      { id: 31, name: '鳥取県', romanized_name: 'Tottori' },
      { id: 32, name: '島根県', romanized_name: 'Shimane' },
      { id: 33, name: '岡山県', romanized_name: 'Okayama' },
      { id: 34, name: '広島県', romanized_name: 'Hiroshima' },
      { id: 35, name: '山口県', romanized_name: 'Yamaguchi' },
      { id: 36, name: '徳島県', romanized_name: 'Tokushima' },
      { id: 37, name: '香川県', romanized_name: 'Kagawa' },
      { id: 38, name: '愛媛県', romanized_name: 'Ehime' },
      { id: 39, name: '高知県', romanized_name: 'Kochi' },
      { id: 40, name: '福岡県', romanized_name: 'Fukuoka' },
      { id: 41, name: '佐賀県', romanized_name: 'Saga' },
      { id: 42, name: '長崎県', romanized_name: 'Nagasaki' },
      { id: 43, name: '熊本県', romanized_name: 'Kumamoto' },
      { id: 44, name: '大分県', romanized_name: 'Oita' },
      { id: 45, name: '宮崎県', romanized_name: 'Miyazaki' },
      { id: 46, name: '鹿児島県', romanized_name: 'Kagoshima' },
      { id: 47, name: '沖縄県', romanized_name: 'Okinawa' }
    ]
  end
end
