# default: &default
#   adapter: mysql2
#   # encoding: utf8mb4
#   encoding: utf8
#   pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
#   username: root
#   password:
#   socket: /tmp/mysql.sock

# development:
#   <<: *default
#   database: SpeBub_development

# test:
#   <<: *default
#   database: SpeBub_test

# production:
#   <<: *default
#   database: SpeBub_production
#   username: SpeBub
#   password: <%= ENV["SPEBUB_DATABASE_PASSWORD"] %>
# # # # # # # # # # # # # # # # # # # # # # # # # # # # # #
# default: &default
#   encoding: utf8
#   pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

# development:
#   <<: *default
#   adapter: mysql2
#   username: root
#   password:
#   host: localhost
#   database: SpeBub_development

# test:
#   <<: *default
#   adapter: mysql2
#   username: root
#   password:
#   host: localhost
#   database: SpeBub_test

# production:
#   <<: *default
#   adapter: postgresql
#   url: <%= ENV['DATABASE_URL'] %>

# # # # # # # # # # # # # # # # # # # # # # # # # # # # # # #
default: &default
  encoding: utf8
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  adapter: postgresql
  database: spebub_development
  username: YOUR_POSTGRES_USERNAME
  password: YOUR_POSTGRES_PASSWORD
  host: localhost

test:
  <<: *default
  adapter: postgresql
  database: spebub_test
  username: YOUR_POSTGRES_USERNAME
  password: YOUR_POSTGRES_PASSWORD
  host: localhost

production:
  <<: *default
  adapter: postgresql
  url: <%= ENV['DATABASE_URL'] %>
