// Configure your import map in config/importmap.rb. Read more: https://github.com/rails/importmap-rails
import "@hotwired/turbo-rails"
import "controllers"
import "ip_address"
import "news_filter"
import "news_new_popup"
import "news_edit_popup"
import "file_preview"
import "image_preview"
import "delete_actions"
import "favorite_news"